### ISSUE TITLE
Update title bar of the Hannover workshop page

### ISSUE THREAD

**Issue by bangerth** [dealii/old-website#13]
@mathmerizing:

The current workshop website at https://www.dealii.org/workshop-2023/ uses the HTML header from a previous workshop, at a time when 9.0 was the current release (see the top of the page). Could we replace this header by the one currently in use by the main page?

**Comment by mathmerizing** [comment]
Should be resolved by #14

**Comment by bangerth** [comment]
It is, thank you!
